{
  "formatVersion": "1.1",
  "component": {
    "group": "net.nikdo53",
    "module": "tiny-multiblock-lib-common-1.20.1",
    "version": "4.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tiny-multiblock-lib-common-1.20.1-4.0.0-sources.jar",
          "url": "tiny-multiblock-lib-common-1.20.1-4.0.0-sources.jar",
          "size": 87186,
          "sha512": "232ba673fce9ff9f0a17da8d929f06897abf15509c7b8f338583c0b7ff61b04ecafa3aed497986c3374e06d270dacc4a600c5ac77e08e97eef36c7c0bebc5dd2",
          "sha256": "982e2c36e0861b1b9d1882cc60b5a3b9a94e28eb6208261a399b7ea8e00babcf",
          "sha1": "cf7f0ac1af417321b1adf18ab9c3952a6a63efa7",
          "md5": "f30ebf62b15e3e84cf08d90fe3c32145"
        }
      ],
      "capabilities": [
        {
          "group": "net.nikdo53",
          "name": "tinymultiblocklib-common-1.20.1",
          "version": "4.0.0"
        },
        {
          "group": "net.nikdo53",
          "name": "tinymultiblocklib",
          "version": "4.0.0"
        },
        {
          "group": "net.nikdo53",
          "name": "tiny-multiblock-lib-common-1.20.1",
          "version": "4.0.0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tiny-multiblock-lib-common-1.20.1-4.0.0-javadoc.jar",
          "url": "tiny-multiblock-lib-common-1.20.1-4.0.0-javadoc.jar",
          "size": 481167,
          "sha512": "46900a3adcb342363fa2efbe41411653f60635e22b9dbc0f25c957350dd8cae05ac256cc2ea8aa7fa1b1e476d6b2dec7f35903bc0c05521f9c40e2d375174f48",
          "sha256": "981c624206c3124be456a53117e8ca87f8bb2ca80a677b62e67b53e1c4138bc3",
          "sha1": "7f1924f263c78ddb57038b8d8bf70898a505e79f",
          "md5": "35943130b2ffcddd96758d30e3eba226"
        }
      ],
      "capabilities": [
        {
          "group": "net.nikdo53",
          "name": "tinymultiblocklib-common-1.20.1",
          "version": "4.0.0"
        },
        {
          "group": "net.nikdo53",
          "name": "tinymultiblocklib",
          "version": "4.0.0"
        },
        {
          "group": "net.nikdo53",
          "name": "tiny-multiblock-lib-common-1.20.1",
          "version": "4.0.0"
        }
      ]
    },
    {
      "name": "reobfRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tiny-multiblock-lib-common-1.20.1-4.0.0.jar",
          "url": "tiny-multiblock-lib-common-1.20.1-4.0.0.jar",
          "size": 175147,
          "sha512": "ad463b2cc96a40cbfd381d77342fadfcfcd5e1d3372ee8733bddb47b1d19b39a81b894b40249687f47e43cad50c3666a31828d5c2233b0d38ab9923b2afbc174",
          "sha256": "2d109e5c279b45772f54c950ca17834f1641ebac172beaa4a020e439054685a3",
          "sha1": "f020e0bb523e2776cb2badd0f3af0f3251edd9e3",
          "md5": "f2507b6b124824129ef769d1dcdfe139"
        }
      ]
    },
    {
      "name": "reobfApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tiny-multiblock-lib-common-1.20.1-4.0.0.jar",
          "url": "tiny-multiblock-lib-common-1.20.1-4.0.0.jar",
          "size": 175147,
          "sha512": "ad463b2cc96a40cbfd381d77342fadfcfcd5e1d3372ee8733bddb47b1d19b39a81b894b40249687f47e43cad50c3666a31828d5c2233b0d38ab9923b2afbc174",
          "sha256": "2d109e5c279b45772f54c950ca17834f1641ebac172beaa4a020e439054685a3",
          "sha1": "f020e0bb523e2776cb2badd0f3af0f3251edd9e3",
          "md5": "f2507b6b124824129ef769d1dcdfe139"
        }
      ]
    }
  ]
}
