{
  "formatVersion": "1.1",
  "component": {
    "group": "net.nikdo53",
    "module": "NeoBackports",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "accessTransformersElements",
      "attributes": {
        "org.gradle.category": "accesstransformer"
      },
      "files": [
        {
          "name": "NeoBackports-1.3.1-accesstransformer.cfg",
          "url": "NeoBackports-1.3.1-accesstransformer.cfg",
          "size": 1020,
          "sha512": "d61eb72f2f99d6fce657e7343538bc7fc482b57b07e444987548e6e4af6669187549dd996d485e81a9383ff618ccad7807cfd16218ef1ea09ded842e9a59a96f",
          "sha256": "f9930b0e78eb5a14280d5ba77afe4c64d6835a854e04a8a2b86d021e7be14c53",
          "sha1": "19f3577e68f2714716aa8facd44d357ee0dca6f1",
          "md5": "70979a0931e3759b46f3caece1849bd1"
        }
      ]
    },
    {
      "name": "interfaceInjectionDataElements",
      "attributes": {
        "org.gradle.category": "interfaceinjection"
      },
      "files": [
        {
          "name": "NeoBackports-1.3.1-interfaceinjection.json",
          "url": "NeoBackports-1.3.1-interfaceinjection.json",
          "size": 3636,
          "sha512": "ed59bdbb4b68d1c6a0f00a2b83858bf78d801d4187606138069dc4ff46bf1b5518c012d427ddfeca405cc706a0c5a71c4e2024379637166024a148d473592615",
          "sha256": "69916b3e8f1ac41aa134f0c14933a2cbf6b255d07be32288d4c1baf45e12d2ef",
          "sha1": "cedeb34d568c4641d05c275947950fd9f9798ca2",
          "md5": "06382433bc4a316ab7c3494dc3624512"
        }
      ]
    },
    {
      "name": "reobfRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NeoBackports-1.3.1.jar",
          "url": "NeoBackports-1.3.1.jar",
          "size": 1071895,
          "sha512": "28da718b0c47ac785010b0ceaa3bd740138fb68e636304ba8f885f2506f3b1d512ab91fd663f857d1bb5fd92d25e051cd7ea9be2bf41a3ecabece73476da432b",
          "sha256": "d85e18f43ed078cc2b8bd6278d728a096317b0e3b1a0990885389ebb6dafa5eb",
          "sha1": "58482990b5d75f8ae36e76ab83af2ca79fc6028b",
          "md5": "641408adc4430546c0453efe5eb6d62d"
        }
      ]
    },
    {
      "name": "reobfApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "NeoBackports-1.3.1.jar",
          "url": "NeoBackports-1.3.1.jar",
          "size": 1071895,
          "sha512": "28da718b0c47ac785010b0ceaa3bd740138fb68e636304ba8f885f2506f3b1d512ab91fd663f857d1bb5fd92d25e051cd7ea9be2bf41a3ecabece73476da432b",
          "sha256": "d85e18f43ed078cc2b8bd6278d728a096317b0e3b1a0990885389ebb6dafa5eb",
          "sha1": "58482990b5d75f8ae36e76ab83af2ca79fc6028b",
          "md5": "641408adc4430546c0453efe5eb6d62d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NeoBackports-1.3.1-javadoc.jar",
          "url": "NeoBackports-1.3.1-javadoc.jar",
          "size": 896292,
          "sha512": "147ddcd10dc72e99b3742c91f4c94d5474933af0f7e4db96b72b5781f47d3f4376773d06730eca12e42c3843922aae5d093141a3243ea1fc83750e653c889e5d",
          "sha256": "36481a7f7afb96d7fccacb8537284c7952d241f81e1f41e03abaeaad52b2d77c",
          "sha1": "46760d1f0f8c863fd72da947c57737472b77340c",
          "md5": "c893cf307db2a97d1e0d9880ded23cde"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NeoBackports-1.3.1-sources.jar",
          "url": "NeoBackports-1.3.1-sources.jar",
          "size": 184532,
          "sha512": "435b0f4218d27028828db9720e11a00ff1e1fed0fcbd82f6b43e1efeb8cb224db2e8b6be809194b94ed4104045cd739037d4d5fe6564b66da6d1ff8948266707",
          "sha256": "1b35b74d19152f2dbbd5b4431c57f863d193f72333cb58837e48372c46bc04a3",
          "sha1": "17f484561f0605d71843df7ec08d5df13292e54e",
          "md5": "20540b6373f0a64fd78f03881b56dcb6"
        }
      ]
    }
  ]
}
