{
  "formatVersion": "1.1",
  "component": {
    "group": "net.nikdo53",
    "module": "tiny-multiblock-lib-common-26.2",
    "version": "4.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "26.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "tiny-multiblock-lib-common-26.2-4.0.1.jar",
          "url": "tiny-multiblock-lib-common-26.2-4.0.1.jar",
          "size": 187777,
          "sha512": "0b4d1be20ed14724852bd319dec9ba6c066c591efb27cc1975ef5d8c6674c8611f315a19a7bde69414265df46a5155091f82fc73dbce9ee32742f51dc07fab55",
          "sha256": "696e590b067a975d98d1e5c4f0dc715aadd8e4294d920f7f60ddca83fc8e0525",
          "sha1": "74071996c2db0c708a47d9f74ecc9254dec1627e",
          "md5": "554228fb711ebf81b17afc6d88fbfe6d"
        }
      ],
      "capabilities": [
        {
          "group": "net.nikdo53",
          "name": "common",
          "version": "4.0.1"
        },
        {
          "group": "net.nikdo53",
          "name": "tiny-multiblock-lib-common-26.2",
          "version": "4.0.1"
        },
        {
          "group": "net.nikdo53",
          "name": "tinymultiblocklib-common-26.2",
          "version": "4.0.1"
        },
        {
          "group": "net.nikdo53",
          "name": "tinymultiblocklib",
          "version": "4.0.1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.nikdo53",
          "module": "nikdo-color",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "26.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "tiny-multiblock-lib-common-26.2-4.0.1.jar",
          "url": "tiny-multiblock-lib-common-26.2-4.0.1.jar",
          "size": 187777,
          "sha512": "0b4d1be20ed14724852bd319dec9ba6c066c591efb27cc1975ef5d8c6674c8611f315a19a7bde69414265df46a5155091f82fc73dbce9ee32742f51dc07fab55",
          "sha256": "696e590b067a975d98d1e5c4f0dc715aadd8e4294d920f7f60ddca83fc8e0525",
          "sha1": "74071996c2db0c708a47d9f74ecc9254dec1627e",
          "md5": "554228fb711ebf81b17afc6d88fbfe6d"
        }
      ],
      "capabilities": [
        {
          "group": "net.nikdo53",
          "name": "common",
          "version": "4.0.1"
        },
        {
          "group": "net.nikdo53",
          "name": "tiny-multiblock-lib-common-26.2",
          "version": "4.0.1"
        },
        {
          "group": "net.nikdo53",
          "name": "tinymultiblocklib-common-26.2",
          "version": "4.0.1"
        },
        {
          "group": "net.nikdo53",
          "name": "tinymultiblocklib",
          "version": "4.0.1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tiny-multiblock-lib-common-26.2-4.0.1-sources.jar",
          "url": "tiny-multiblock-lib-common-26.2-4.0.1-sources.jar",
          "size": 95366,
          "sha512": "4b09aaa9d9da9cf5f51a266d1f3ad1afbd94d4b8adff49abefeb51555a70179bf7e0248226d6d11a5c6e1e4e5b426dd275261dd0b99107bf0417f9a3d44f6f82",
          "sha256": "aa83116eba057747c9861d695b7e2d62e6048c9dc6bdbc5706e4a23b889512c4",
          "sha1": "a765f22543d7eef1511796911e85d907202fe838",
          "md5": "752925012242ff9216ff8674fa0a3db6"
        }
      ],
      "capabilities": [
        {
          "group": "net.nikdo53",
          "name": "common",
          "version": "4.0.1"
        },
        {
          "group": "net.nikdo53",
          "name": "tiny-multiblock-lib-common-26.2",
          "version": "4.0.1"
        },
        {
          "group": "net.nikdo53",
          "name": "tinymultiblocklib-common-26.2",
          "version": "4.0.1"
        },
        {
          "group": "net.nikdo53",
          "name": "tinymultiblocklib",
          "version": "4.0.1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tiny-multiblock-lib-common-26.2-4.0.1-javadoc.jar",
          "url": "tiny-multiblock-lib-common-26.2-4.0.1-javadoc.jar",
          "size": 4624012,
          "sha512": "8029d28e169547bc976464c478df52399a24a9c797853254ff7bec0d943fe84336b74a6b1b948670a6ee3b0323fc828294e8742b590378469ad211b2245325fb",
          "sha256": "59ed86b7c1bf9fbf649574ef32a625d2b8cf4d4045dcee46c79a4cd22f2003ed",
          "sha1": "aa6cc0aada03367853dfe9ac848501084663f3cc",
          "md5": "6fe9f961a087389694efce9625a650ba"
        }
      ],
      "capabilities": [
        {
          "group": "net.nikdo53",
          "name": "common",
          "version": "4.0.1"
        },
        {
          "group": "net.nikdo53",
          "name": "tiny-multiblock-lib-common-26.2",
          "version": "4.0.1"
        },
        {
          "group": "net.nikdo53",
          "name": "tinymultiblocklib-common-26.2",
          "version": "4.0.1"
        },
        {
          "group": "net.nikdo53",
          "name": "tinymultiblocklib",
          "version": "4.0.1"
        }
      ]
    }
  ]
}
