{
  "formatVersion": "1.1",
  "component": {
    "group": "net.nikdo53",
    "module": "tiny-multiblock-lib-fabric-1.21.1",
    "version": "4.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tiny-multiblock-lib-fabric-1.21.1-4.0.0.jar",
          "url": "tiny-multiblock-lib-fabric-1.21.1-4.0.0.jar",
          "size": 214525,
          "sha512": "8884b988ebcf0d1d77fe3ff5dba7eef36e198cb6c773efe28c05f50b6554791715c48d0aea446906685cad6c6b1efaac03993dc043254ce8a8fd692b5a9c6b40",
          "sha256": "ab26c34bfebd6a0e07d9a926cc169aa887abdfe3e8f38ca69bd326675923a4e2",
          "sha1": "2bc0edaedf9dca7bff85132b38dca8c877233ea8",
          "md5": "ff45d10be867504a288b35d5840246a4"
        }
      ],
      "capabilities": [
        {
          "group": "net.nikdo53",
          "name": "tinymultiblocklib-fabric-1.21.1",
          "version": "4.0.0"
        },
        {
          "group": "net.nikdo53",
          "name": "tinymultiblocklib",
          "version": "4.0.0"
        },
        {
          "group": "net.nikdo53",
          "name": "tiny-multiblock-lib-fabric-1.21.1",
          "version": "4.0.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "net.nikdo53",
          "module": "nikdo-color",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.0+1.21.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "tiny-multiblock-lib-fabric-1.21.1-4.0.0.jar",
          "url": "tiny-multiblock-lib-fabric-1.21.1-4.0.0.jar",
          "size": 214525,
          "sha512": "8884b988ebcf0d1d77fe3ff5dba7eef36e198cb6c773efe28c05f50b6554791715c48d0aea446906685cad6c6b1efaac03993dc043254ce8a8fd692b5a9c6b40",
          "sha256": "ab26c34bfebd6a0e07d9a926cc169aa887abdfe3e8f38ca69bd326675923a4e2",
          "sha1": "2bc0edaedf9dca7bff85132b38dca8c877233ea8",
          "md5": "ff45d10be867504a288b35d5840246a4"
        }
      ],
      "capabilities": [
        {
          "group": "net.nikdo53",
          "name": "tinymultiblocklib-fabric-1.21.1",
          "version": "4.0.0"
        },
        {
          "group": "net.nikdo53",
          "name": "tinymultiblocklib",
          "version": "4.0.0"
        },
        {
          "group": "net.nikdo53",
          "name": "tiny-multiblock-lib-fabric-1.21.1",
          "version": "4.0.0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tiny-multiblock-lib-fabric-1.21.1-4.0.0-sources.jar",
          "url": "tiny-multiblock-lib-fabric-1.21.1-4.0.0-sources.jar",
          "size": 96596,
          "sha512": "b3efd5c25072a39f080da761c5c9a3287ec2f0f10a34c05128c0362ce2ad1d0cee26339ac34439b274bac3073eb4740d394b53ddc1a8089f1b1e9ce475a0dd00",
          "sha256": "cf31d357e6db5699ad5eb046e6320d5bcd5c9cd94a1a374dec1ae5c04d92932c",
          "sha1": "9431387bc033a450fdf0514a61f423515fc3db7b",
          "md5": "83da5abe5ca1cdcbea38b53e80e9625b"
        }
      ],
      "capabilities": [
        {
          "group": "net.nikdo53",
          "name": "tinymultiblocklib-fabric-1.21.1",
          "version": "4.0.0"
        },
        {
          "group": "net.nikdo53",
          "name": "tinymultiblocklib",
          "version": "4.0.0"
        },
        {
          "group": "net.nikdo53",
          "name": "tiny-multiblock-lib-fabric-1.21.1",
          "version": "4.0.0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tiny-multiblock-lib-fabric-1.21.1-4.0.0-javadoc.jar",
          "url": "tiny-multiblock-lib-fabric-1.21.1-4.0.0-javadoc.jar",
          "size": 553109,
          "sha512": "2e92ad8ed5312389f9312ee18efa99f9d4eeee882689b7817d0d11cc75c4350fb4dd92ebdc372330c863f13d0f7913c5834a151e084c91af9666898299dd06b5",
          "sha256": "b6721424d9402d36615948e08ae00f69e1110ed23aa1b49b65ef34557a860abf",
          "sha1": "a46cace4f918051ea6f0bf5103d47a5ea0affab9",
          "md5": "dc2aded48b6ed148df8331a6f113ddc9"
        }
      ],
      "capabilities": [
        {
          "group": "net.nikdo53",
          "name": "tinymultiblocklib-fabric-1.21.1",
          "version": "4.0.0"
        },
        {
          "group": "net.nikdo53",
          "name": "tinymultiblocklib",
          "version": "4.0.0"
        },
        {
          "group": "net.nikdo53",
          "name": "tiny-multiblock-lib-fabric-1.21.1",
          "version": "4.0.0"
        }
      ]
    }
  ]
}
