{
  "formatVersion": "1.1",
  "component": {
    "group": "net.nikdo53",
    "module": "NeoBackports",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "accessTransformersElements",
      "attributes": {
        "org.gradle.category": "accesstransformer"
      },
      "files": [
        {
          "name": "NeoBackports-1.3.0-accesstransformer.cfg",
          "url": "NeoBackports-1.3.0-accesstransformer.cfg",
          "size": 1020,
          "sha512": "d61eb72f2f99d6fce657e7343538bc7fc482b57b07e444987548e6e4af6669187549dd996d485e81a9383ff618ccad7807cfd16218ef1ea09ded842e9a59a96f",
          "sha256": "f9930b0e78eb5a14280d5ba77afe4c64d6835a854e04a8a2b86d021e7be14c53",
          "sha1": "19f3577e68f2714716aa8facd44d357ee0dca6f1",
          "md5": "70979a0931e3759b46f3caece1849bd1"
        }
      ]
    },
    {
      "name": "interfaceInjectionDataElements",
      "attributes": {
        "org.gradle.category": "interfaceinjection"
      },
      "files": [
        {
          "name": "NeoBackports-1.3.0-interfaceinjection.json",
          "url": "NeoBackports-1.3.0-interfaceinjection.json",
          "size": 3636,
          "sha512": "ed59bdbb4b68d1c6a0f00a2b83858bf78d801d4187606138069dc4ff46bf1b5518c012d427ddfeca405cc706a0c5a71c4e2024379637166024a148d473592615",
          "sha256": "69916b3e8f1ac41aa134f0c14933a2cbf6b255d07be32288d4c1baf45e12d2ef",
          "sha1": "cedeb34d568c4641d05c275947950fd9f9798ca2",
          "md5": "06382433bc4a316ab7c3494dc3624512"
        }
      ]
    },
    {
      "name": "reobfRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NeoBackports-1.3.0.jar",
          "url": "NeoBackports-1.3.0.jar",
          "size": 1071862,
          "sha512": "95d941a1dacd1afedc919568413c7fa36399cb53e2a0886c4cd3ec55548faa67b9ce400665b430ab792e9012cba47b21a8817a7aa7e41e0f1f9a6bd1c74efcc1",
          "sha256": "724153d3c916ccb6f98f9e29cfac33880f15ebb501bbeacd9178802f15044e45",
          "sha1": "1288c3cb54e04c4aad0013039ecf0a04aad8b930",
          "md5": "8c2d9856f733de948861a806fdcf0467"
        }
      ]
    },
    {
      "name": "reobfApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "NeoBackports-1.3.0.jar",
          "url": "NeoBackports-1.3.0.jar",
          "size": 1071862,
          "sha512": "95d941a1dacd1afedc919568413c7fa36399cb53e2a0886c4cd3ec55548faa67b9ce400665b430ab792e9012cba47b21a8817a7aa7e41e0f1f9a6bd1c74efcc1",
          "sha256": "724153d3c916ccb6f98f9e29cfac33880f15ebb501bbeacd9178802f15044e45",
          "sha1": "1288c3cb54e04c4aad0013039ecf0a04aad8b930",
          "md5": "8c2d9856f733de948861a806fdcf0467"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NeoBackports-1.3.0-javadoc.jar",
          "url": "NeoBackports-1.3.0-javadoc.jar",
          "size": 896382,
          "sha512": "2f124ed6068d3f61c3f1733ebf5b4f16ba3dea5df79254919b950b5073d56567811f645f74e27c2f36ec3f77e83512e4e8a21691ba70e0dc9740f8e73e53e1ff",
          "sha256": "33289828295173d46a10320d579b173e5f1ad699b4a0dff9c79fdaec4b54facb",
          "sha1": "c728073c94b7c01644faf90e2b00e1994d812f2f",
          "md5": "3fb47a9ea6b09b553702feadbea9f328"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NeoBackports-1.3.0-sources.jar",
          "url": "NeoBackports-1.3.0-sources.jar",
          "size": 184518,
          "sha512": "5cf7a70d785e4d7df25c63a8d89b63c33c9c4597727edbfdfc816a88d214237a814a973a7c9c21621cd70af8b7b0c47090b38d0e38d06ea41fe67ec0a06f2568",
          "sha256": "1d8a56d690e8ee8931b0a1f16de63c297cdcaa591f24419d41f41b97ad4e1116",
          "sha1": "82e2a6f0d2252a56df96b00ced2c1fe332a954ab",
          "md5": "ac60baeba4775ff25335eb4e5329ecdd"
        }
      ]
    }
  ]
}
