{
  "formatVersion": "1.1",
  "component": {
    "group": "net.nikdo53",
    "module": "tiny-multiblock-lib-forge-1.20.1",
    "version": "4.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tiny-multiblock-lib-forge-1.20.1-4.0.0-sources.jar",
          "url": "tiny-multiblock-lib-forge-1.20.1-4.0.0-sources.jar",
          "size": 96191,
          "sha512": "f208f3525dc801217bc64f3391187f9985ab30ffc1d41c66c3570b7d13cd8722344b4ca0e8aa023c9b187c5e891f865ab7fd90f31e0fa95e34cda418d8aa0356",
          "sha256": "bc9a537f5a8bfd2860ec933d0f7e643df4effdd9e77a432e934ed3a59105ae14",
          "sha1": "bc2eba603eb532d6037bd8693bf339134fa54eb7",
          "md5": "8f3dcae5c7741be7e896a8cf09f86907"
        }
      ],
      "capabilities": [
        {
          "group": "net.nikdo53",
          "name": "tinymultiblocklib",
          "version": "4.0.0"
        },
        {
          "group": "net.nikdo53",
          "name": "tiny-multiblock-lib-neoforge-1.20.1",
          "version": "4.0.0"
        },
        {
          "group": "net.nikdo53",
          "name": "tinymultiblocklib-neoforge-1.20.1",
          "version": "4.0.0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tiny-multiblock-lib-forge-1.20.1-4.0.0-javadoc.jar",
          "url": "tiny-multiblock-lib-forge-1.20.1-4.0.0-javadoc.jar",
          "size": 532020,
          "sha512": "679f4e0d6a93825eaf5a4f711c84b54769060b8e22f3f3ffe491e4b8fa77dd5af13390613c7bb0ba9ff30afd644299880614cd9681c4f1d7b3dc72d6484345b9",
          "sha256": "316e7b8b6b40e4a9cc86b5717f5604c876aab1df898b34af32ed229f9a6b8d5e",
          "sha1": "93cd0642b23b7b3ab518ceeb3a498c794fe3d415",
          "md5": "54ad562276b85f5ede00b3400d28ea22"
        }
      ],
      "capabilities": [
        {
          "group": "net.nikdo53",
          "name": "tinymultiblocklib",
          "version": "4.0.0"
        },
        {
          "group": "net.nikdo53",
          "name": "tiny-multiblock-lib-neoforge-1.20.1",
          "version": "4.0.0"
        },
        {
          "group": "net.nikdo53",
          "name": "tinymultiblocklib-neoforge-1.20.1",
          "version": "4.0.0"
        }
      ]
    },
    {
      "name": "reobfRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tiny-multiblock-lib-forge-1.20.1-4.0.0.jar",
          "url": "tiny-multiblock-lib-forge-1.20.1-4.0.0.jar",
          "size": 846025,
          "sha512": "9edfa2f6dab558bf35f3b444ec2b40c463394fc24dbf72521eee3840b3fc154d404df4595a0bac46f0bb1b2dc16a1bc74a8e56eb0624cbe22b910a1b5f79b90d",
          "sha256": "79dffffc9115059b3ddd8290708f388245d3489b61d20399e9b6d5095ddc8e01",
          "sha1": "355fce0c9d8d3755fa561ac30d201a035a509dd6",
          "md5": "004aec0a159d4e817ac1458ed4c040a6"
        }
      ]
    },
    {
      "name": "reobfApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tiny-multiblock-lib-forge-1.20.1-4.0.0.jar",
          "url": "tiny-multiblock-lib-forge-1.20.1-4.0.0.jar",
          "size": 846025,
          "sha512": "9edfa2f6dab558bf35f3b444ec2b40c463394fc24dbf72521eee3840b3fc154d404df4595a0bac46f0bb1b2dc16a1bc74a8e56eb0624cbe22b910a1b5f79b90d",
          "sha256": "79dffffc9115059b3ddd8290708f388245d3489b61d20399e9b6d5095ddc8e01",
          "sha1": "355fce0c9d8d3755fa561ac30d201a035a509dd6",
          "md5": "004aec0a159d4e817ac1458ed4c040a6"
        }
      ]
    }
  ]
}
