{
  "formatVersion": "1.1",
  "component": {
    "group": "net.nikdo53",
    "module": "tiny-multiblock-lib-fabric-1.20.1",
    "version": "4.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tiny-multiblock-lib-fabric-1.20.1-4.0.0.jar",
          "url": "tiny-multiblock-lib-fabric-1.20.1-4.0.0.jar",
          "size": 211337,
          "sha512": "5beb78471f007458121030c4e042c3560d792378209a7da90636e6b4f3e55d99ea2ebb85013b1b15df420f31cba31d47d8aa60d7dcd9fef1eeb237811c94bfa7",
          "sha256": "94a4ccddca74a553e603eb46ed270aebeb784f237d5e8b1eb6956904ed2f9fa1",
          "sha1": "7bb216a314c954f503b15cd041772542ae5e3d98",
          "md5": "501907c880bd8475cb82d5893640e291"
        }
      ],
      "capabilities": [
        {
          "group": "net.nikdo53",
          "name": "tinymultiblocklib-fabric-1.20.1",
          "version": "4.0.0"
        },
        {
          "group": "net.nikdo53",
          "name": "tinymultiblocklib",
          "version": "4.0.0"
        },
        {
          "group": "net.nikdo53",
          "name": "tiny-multiblock-lib-fabric-1.20.1",
          "version": "4.0.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "net.nikdo53",
          "module": "nikdo-color",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.1+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "tiny-multiblock-lib-fabric-1.20.1-4.0.0.jar",
          "url": "tiny-multiblock-lib-fabric-1.20.1-4.0.0.jar",
          "size": 211337,
          "sha512": "5beb78471f007458121030c4e042c3560d792378209a7da90636e6b4f3e55d99ea2ebb85013b1b15df420f31cba31d47d8aa60d7dcd9fef1eeb237811c94bfa7",
          "sha256": "94a4ccddca74a553e603eb46ed270aebeb784f237d5e8b1eb6956904ed2f9fa1",
          "sha1": "7bb216a314c954f503b15cd041772542ae5e3d98",
          "md5": "501907c880bd8475cb82d5893640e291"
        }
      ],
      "capabilities": [
        {
          "group": "net.nikdo53",
          "name": "tinymultiblocklib-fabric-1.20.1",
          "version": "4.0.0"
        },
        {
          "group": "net.nikdo53",
          "name": "tinymultiblocklib",
          "version": "4.0.0"
        },
        {
          "group": "net.nikdo53",
          "name": "tiny-multiblock-lib-fabric-1.20.1",
          "version": "4.0.0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tiny-multiblock-lib-fabric-1.20.1-4.0.0-sources.jar",
          "url": "tiny-multiblock-lib-fabric-1.20.1-4.0.0-sources.jar",
          "size": 95872,
          "sha512": "ddbecd5f5cfb4b5e0d8cea77af890f58e564463b51d09addf3159ebcfd135f97ed836bafb09cdda5f3a20f414093a660fc3dc26fec88d77cabefd028e0cc6320",
          "sha256": "25b49e2159fb589e6fa210d89139f90a03dd313f9586eebd06d4d5a8f70ccf93",
          "sha1": "9ad440384a27a9a337793f51dedb22e8178d8e4a",
          "md5": "e2e0c23c412f4332143d0fe5ada5c3cb"
        }
      ],
      "capabilities": [
        {
          "group": "net.nikdo53",
          "name": "tinymultiblocklib-fabric-1.20.1",
          "version": "4.0.0"
        },
        {
          "group": "net.nikdo53",
          "name": "tinymultiblocklib",
          "version": "4.0.0"
        },
        {
          "group": "net.nikdo53",
          "name": "tiny-multiblock-lib-fabric-1.20.1",
          "version": "4.0.0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tiny-multiblock-lib-fabric-1.20.1-4.0.0-javadoc.jar",
          "url": "tiny-multiblock-lib-fabric-1.20.1-4.0.0-javadoc.jar",
          "size": 528201,
          "sha512": "4758f61c7f3f8300c05157a5371fd051fab268ce128cbf0231e36e5fe0abed48fbd2624c695ed83ec3e87e6d4ef3e0476a5b453e99a74a7ffe420b49b97d8221",
          "sha256": "bb1e8ea1ec6aef7e1c5cbc08d9e45a8b476536bf0f9ef554d375f2b52636a1f1",
          "sha1": "c8bda9da6e5a684c111aa08272728bd38d201403",
          "md5": "98e4e5ff84fafe1790112df8d0f02762"
        }
      ],
      "capabilities": [
        {
          "group": "net.nikdo53",
          "name": "tinymultiblocklib-fabric-1.20.1",
          "version": "4.0.0"
        },
        {
          "group": "net.nikdo53",
          "name": "tinymultiblocklib",
          "version": "4.0.0"
        },
        {
          "group": "net.nikdo53",
          "name": "tiny-multiblock-lib-fabric-1.20.1",
          "version": "4.0.0"
        }
      ]
    }
  ]
}
