{
  "formatVersion": "1.1",
  "component": {
    "group": "net.nikdo53",
    "module": "tiny-multiblock-lib-fabric-1.20.1",
    "version": "4.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tiny-multiblock-lib-fabric-1.20.1-4.0.0.jar",
          "url": "tiny-multiblock-lib-fabric-1.20.1-4.0.0.jar",
          "size": 211345,
          "sha512": "7888fc02911b449be237f9ec55c934686c0a47e6307ebf24de59d01e6926a3ef76fe885a99f3214393894fe7054e1eb551eb5ac2b051c87fe10ea4174edcdd14",
          "sha256": "8aa075b6be69ded434c651fd17c2942e262dc111830338da3344db92bada416b",
          "sha1": "67e7f6587577b2b1c7e0ee582ee39852f4474cab",
          "md5": "cf0b63b22ed5c85d41f0721da7004796"
        }
      ],
      "capabilities": [
        {
          "group": "net.nikdo53",
          "name": "tinymultiblocklib-fabric-1.20.1",
          "version": "4.0.0"
        },
        {
          "group": "net.nikdo53",
          "name": "tinymultiblocklib",
          "version": "4.0.0"
        },
        {
          "group": "net.nikdo53",
          "name": "tiny-multiblock-lib-fabric-1.20.1",
          "version": "4.0.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "net.nikdo53",
          "module": "nikdo-color",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.1+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "tiny-multiblock-lib-fabric-1.20.1-4.0.0.jar",
          "url": "tiny-multiblock-lib-fabric-1.20.1-4.0.0.jar",
          "size": 211345,
          "sha512": "7888fc02911b449be237f9ec55c934686c0a47e6307ebf24de59d01e6926a3ef76fe885a99f3214393894fe7054e1eb551eb5ac2b051c87fe10ea4174edcdd14",
          "sha256": "8aa075b6be69ded434c651fd17c2942e262dc111830338da3344db92bada416b",
          "sha1": "67e7f6587577b2b1c7e0ee582ee39852f4474cab",
          "md5": "cf0b63b22ed5c85d41f0721da7004796"
        }
      ],
      "capabilities": [
        {
          "group": "net.nikdo53",
          "name": "tinymultiblocklib-fabric-1.20.1",
          "version": "4.0.0"
        },
        {
          "group": "net.nikdo53",
          "name": "tinymultiblocklib",
          "version": "4.0.0"
        },
        {
          "group": "net.nikdo53",
          "name": "tiny-multiblock-lib-fabric-1.20.1",
          "version": "4.0.0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tiny-multiblock-lib-fabric-1.20.1-4.0.0-sources.jar",
          "url": "tiny-multiblock-lib-fabric-1.20.1-4.0.0-sources.jar",
          "size": 95795,
          "sha512": "928a1bd4a08ef056c37b6c0f5159208bd5be1ddf523dba4ccd747a97c42213e77081cdda96fc17fc2157a153ddc3224b1cb44f7e6fc417d6308077d55a92b986",
          "sha256": "dfa1aafab762a58b3e88df962062638bbc115becc73ea7fc1e3f144a4a70cc84",
          "sha1": "cf8c35856772fb4580463cf8f5b7aed11ea59c38",
          "md5": "a31419f3415cc6e7e87505d7008b091d"
        }
      ],
      "capabilities": [
        {
          "group": "net.nikdo53",
          "name": "tinymultiblocklib-fabric-1.20.1",
          "version": "4.0.0"
        },
        {
          "group": "net.nikdo53",
          "name": "tinymultiblocklib",
          "version": "4.0.0"
        },
        {
          "group": "net.nikdo53",
          "name": "tiny-multiblock-lib-fabric-1.20.1",
          "version": "4.0.0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tiny-multiblock-lib-fabric-1.20.1-4.0.0-javadoc.jar",
          "url": "tiny-multiblock-lib-fabric-1.20.1-4.0.0-javadoc.jar",
          "size": 528181,
          "sha512": "d8aea66f1af0726867ee648709fb7a0648a777c521f6b8053eff76dd834a835502812f6cec748930240fc7cf5de1bf5b6a6d4b113018a87dd0686ce076722ba5",
          "sha256": "af4390e9a246ed528c7281f81f47b1ad7056d5065a4a29c68dad75fe27deedb2",
          "sha1": "758e6bdbea830e7d5ff1d19d867a2e0401d45bd4",
          "md5": "4106f7b81c7785d6f508e53077d46a2e"
        }
      ],
      "capabilities": [
        {
          "group": "net.nikdo53",
          "name": "tinymultiblocklib-fabric-1.20.1",
          "version": "4.0.0"
        },
        {
          "group": "net.nikdo53",
          "name": "tinymultiblocklib",
          "version": "4.0.0"
        },
        {
          "group": "net.nikdo53",
          "name": "tiny-multiblock-lib-fabric-1.20.1",
          "version": "4.0.0"
        }
      ]
    }
  ]
}
